Add files via upload

diff --git a/system b/system
--- a/system
+++ b/system
@@ -140,9 +140,23 @@ set_timezone() {
 	geoip_tz="$(wget -q -O- 'http://ip-api.com/line/?fields=timezone')"
 	geoip_tz_continent="$(echo "$geoip_tz" | cut -d / -f1)"
 	geoip_tz_city="$(echo "$geoip_tz" | cut -d / -f2)"
-	tz_continent="$(ls -1 -d /usr/share/zoneinfo/*/ | cut -d / -f5 | fzy -p "select a continent: " -q "$geoip_tz_continent")"
-	tz_city="$(ls -1 /usr/share/zoneinfo/"$tz_continent"/* | cut -d / -f6 | fzy -p "select a city: " -q "$geoip_tz_city")"
-	ln -sf "/usr/share/zoneinfo/${tz_continent}/${tz_city}" /etc/localtime
+	tz_continent="$(ls -1 -d /usr/share/zoneinfo/*/ | cut -d / -f5 |
+		fzy -p "select a continent: " -q "$geoip_tz_continent")"
+	tz_city="$(ls -1 /usr/share/zoneinfo/"$tz_continent"/* | cut -d / -f6 |
+		fzy -p "select a city: " -q "$geoip_tz_city")"
+	timedatectl set-timezone "${tz_continent}/${tz_city}"
+}
+
+change_passwords() {
+	local answer="$(printf "user password\nsudo password" | fzy)"
+	
+	[ "$answer" = "user password" ] && while ! passwd --quiet; do
+		echo "an error occured; please try again"
+	done
+	
+	[ "$answer" = "sudo password" ] && while ! sudo passwd --quiet; do
+		echo "an error occured; please try again"
+	done
 }
 
 manage_packages() {
@@ -171,18 +185,6 @@ manage_packages() {
 	}
 	
 	sudo /usr/local/bin/system-packages "$mode" "$package_name"
-}
-
-change_passwords() {
-	local answer="$(printf "user password\nsudo password" | fzy)"
-	
-	[ "$answer" = "user password" ] && while ! passwd --quiet; do
-		echo "an error occured; please try again"
-	done
-	
-	[ "$answer" = "sudo password" ] && while ! sudo passwd --quiet; do
-		echo "an error occured; please try again"
-	done
 }
 
 if [ -z "$1" ]; then
